services:
  backend:
    image: rushi1501/notes-backend:latest
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/devoops-notes
      PORT: 3000
    depends_on:
      - mongo

  frontend:
    image: rushi1501/notes-frontend:latest
    restart: always

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
  mongo-data:
