services:
  backend:
    container_name: backend
    build: ./Backend
    image: rushi1501/notes-backend:latest
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/devoops-notes
      PORT: 3000
    depends_on:
      - mongo

  frontend:
    container_name: frontend
    build:
      context: ./Frontend
      args:
        VITE_BACKEND_URL: http://backend:3000
        
    image: rushi1501/notes-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
